version: 0.0
os: linux
files:
  - source: petclinic.war
    destination: /usr/share/tomcat7/webapps/petclinic.war
hooks:
  AfterInstall:
    - location: codedeploy/afterInstall.sh
      timeout: 300
      runas: root
