version: 0.0
os: linux
files:
  - source: /target/petclinic.war
    destination: /usr/share/tomcat/webapps/petclinic.war
hooks:
  AfterInstall:
    - location: codedeploy/afterInstall.sh
      timeout: 300
      runas: root
